# Target specific macros
TARGET = test
TARGET_SOURCES := main.c path.c util.c motorController.c feed.c calibrate.c
TOPPERS_OSEK_OIL_SOURCE := main.oil

O_PATH ?= build

include ~/nxtOSEK/ecrobot/ecrobot.mak
