#ifndef SYM_H
#define SYM_H

#define ARM_MOTOR_PORT 0

#define OPTIMAL_LIGHT_VALUE 200
#define MAX_STEERING_ANGLE 40
#define DEFAULT_TURN_POSITION 180
#define PATH_SENSOR_PORT NXT_PORT_S1
#define TRANSLATIONFACTOR MAX_STEERING_ANGLE / OPTIMAL_LIGHT_VALUE
#define PLANT_SENSOR_PORT NXT_PORT_S2

#endif
